name: Build and test
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - name: Test direct build and localizations
        run: ./script/test.sh
