name: Build and test
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: Test direct build and localizations
        run: ./script/test.sh
